import { type level, type ScoreValue, type text } from "../stores/levels";

interface TextTemplate {
  messages: text[];
  isScam: boolean;
  correctAnswer: "safe" | "sus" | "threat";
  feedbackSafe: string;
  feedbackSus: string;
  feedbackThreat: string;
}

const easyTemplates: TextTemplate[] = [
  {
    messages: [
      {
        sender: "incoming",
        content: "Your Google verification code is 883902. Do not share this code with anyone.",
      },
    ],
    isScam: false,
    correctAnswer: "safe",
    feedbackSafe: "Correct! Standard two-factor authentication codes sent upon request are safe.",
    feedbackSus: "While you should never share these codes, receiving one you requested is normal and safe.",
    feedbackThreat: "No threat here. This is a standard 2FA code generated by Google when logging in.",
  },
  {
    messages: [
      {
        sender: "incoming",
        content: "Your Uber ride is arriving! Look for a silver Toyota Camry (license plate 7XYZ89) driven by Carlos.",
      },
    ],
    isScam: false,
    correctAnswer: "safe",
    feedbackSafe: "Exactly! This is a legitimate ride status update from Uber.",
    feedbackSus: "A bit overly cautious! This is a normal notification detailing a requested ride.",
    feedbackThreat: "No threat here! It is just a standard vehicle description for your Uber pickup.",
  },
  {
    messages: [
      {
        sender: "incoming",
        content: "CONGRATS! You won a free $1000 Walmart Gift Card! Click here to claim: http://walmart-freebies.biz",
      },
      {
        sender: "outgoing",
        content: "Wait really? Is this real?",
      },
    ],
    isScam: true,
    correctAnswer: "threat",
    feedbackSafe: "Be careful! Random messages claiming you won huge gift cards from weird '.biz' URLs are always scams.",
    feedbackSus: "It's smart to ask, but this is a clear phishing scam designed to steal your information.",
    feedbackThreat: "Excellent work! Major companies don't send text notifications of massive prizes with suspicious domain names.",
  },
  {
    messages: [
      {
        sender: "incoming",
        content: "Hi Mom, I dropped my phone in the toilet. I'm using a friend's phone. Can you Venmo $250 to fix it? I'm stranded!",
      },
    ],
    isScam: true,
    correctAnswer: "threat",
    feedbackSafe: "Wait! Always call your family member on their actual phone number to verify first. Scammers love pretending to be relatives.",
    feedbackSus: "Excellent suspicion. Emergency money requests from unknown numbers should always be treated with extreme caution.",
    feedbackThreat: "Awesome detection! This 'kid in distress' routine is a very popular social engineering tactic.",
  },
];

const intermediateTemplates: TextTemplate[] = [
  {
    messages: [
      {
        sender: "incoming",
        content: "Chase Fraud Alert: Did you spend $45.20 at Target? Reply YES or NO.",
      },
      {
        sender: "outgoing",
        content: "NO",
      },
      {
        sender: "incoming",
        content: "Thank you. To secure your account, please call us at the number on the back of your card or visit chase.com.",
      },
    ],
    isScam: false,
    correctAnswer: "safe",
    feedbackSafe: "Spot on! The text tells you to use the official phone number on your card or the official website, which is safe and secure.",
    feedbackSus: "It's good to be cautious, but notice how they didn't supply a shady direct link. They told you to call the number on your card.",
    feedbackThreat: "This text is not a threat. It is a real security alert from Chase telling you to use trusted channels.",
  },
  {
    messages: [
      {
        sender: "incoming",
        content: "Hi Sarah, are we still meeting for lunch today? - Mark",
      },
      {
        sender: "outgoing",
        content: "Sorry, wrong number! I'm not Sarah.",
      },
      {
        sender: "incoming",
        content: "Oh, sorry! Well, you seem very polite anyway. I'm Mark, what's your name? Maybe it's fate haha",
      },
    ],
    isScam: true,
    correctAnswer: "sus",
    feedbackSafe: "Watch out! Real people will just apologize and stop texting. Scammers keep chatting to build fake relationships.",
    feedbackSus: "Brilliant! This 'wrong number' routine is a common prelude to investment scams (like cryptocurrency traps).",
    feedbackThreat: "This conversation is definitely suspicious (sus). They haven't asked for money yet, but they're laying the hook.",
  },
  {
    messages: [
      {
        sender: "incoming",
        content: "WellsFargo Security Alert: We detected a suspicious login attempt from Texas. Lock your account: http://wellsfargo-secure-login.net",
      },
    ],
    isScam: true,
    correctAnswer: "threat",
    feedbackSafe: "Careful! Wells Fargo will never ask you to lock your account using a non-official URL like 'wellsfargo-secure-login.net'.",
    feedbackSus: "Good job flagging. The urgent tone is suspect, and the URL is definitely not Wells Fargo's real domain.",
    feedbackThreat: "Exactly! Phishing texts copy official alerts but send you to a credential-harvesting lookalike site.",
  },
];

const hardTemplates: TextTemplate[] = [
  {
    messages: [
      {
        sender: "incoming",
        content: "FRM: CITIBANK. MSG: Your card ending in 9081 has a temporary hold. Call 888-248-4226.",
      },
    ],
    isScam: false,
    correctAnswer: "safe",
    feedbackSafe: "Correct! Citibank uses shortcodes and formal formats to issue hold notifications. (Always call the number on your official card to double check!)",
    feedbackSus: "A suspicious look is warranted since scammers send fake bank alerts, but standard bank shortcodes without hyperlinks are generally safe.",
    feedbackThreat: "No threat here. This is a classic fraud notification format, but it's safe to verify via the card's official customer service line.",
  },
  {
    messages: [
      {
        sender: "incoming",
        content: "USPS Alert: Your package delivery has been paused due to an incorrect address. Fix it here: https://usps-post.info",
      },
    ],
    isScam: true,
    correctAnswer: "threat",
    feedbackSafe: "No! The official US Postal Service will only ever send you to 'usps.com', never a '.info' site.",
    feedbackSus: "Good job holding back. Smishing package delivery links are extremely prevalent scams.",
    feedbackThreat: "Outstanding! This is a textbook package delivery phishing link using lookalike domains to steal cards and addresses.",
  },
  {
    messages: [
      {
        sender: "incoming",
        content: "Hey, it's John (your boss). I'm in a conference call right now. Can you run to the store and get 3 $100 Steam gift cards for a client presentation? Send me photos of the backs.",
      },
    ],
    isScam: true,
    correctAnswer: "threat",
    feedbackSafe: "Watch out! Bosses and supervisors will never demand that you purchase gift cards with your own money via a text text.",
    feedbackSus: "Excellent call. Always verify such requests by calling your boss or using official internal corporate channels.",
    feedbackThreat: "Great eye! Boss impersonation scams via SMS targeting gift cards are highly common phishing attacks.",
  },
];

export function generateTextLevel(difficulty: "easy" | "intermediate" | "hard"): level {
  let pool = easyTemplates;
  if (difficulty === "intermediate") {
    pool = intermediateTemplates;
  } else if (difficulty === "hard") {
    pool = hardTemplates;
  }

  // Pick a random template from the pool
  const template = pool[Math.floor(Math.random() * pool.length)];

  // Set up score values based on correct answer
  const scoreValues: ScoreValue[] = [
    {
      name: "safe",
      value: template.correctAnswer === "safe" ? 1 : 0,
      feedback: template.feedbackSafe,
    },
    {
      name: "sus",
      value: template.correctAnswer === "sus" ? 1 : 0.5,
      feedback: template.feedbackSus,
    },
    {
      name: "threat",
      value: template.correctAnswer === "threat" ? 1 : 0,
      feedback: template.feedbackThreat,
    },
  ];

  return {
    contentType: "text",
    content: template.messages,
    scoreValues,
  };
}
